// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyrkunvidrkgdosmghzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5cmt1bnZpZHJrZ2Rvc21naHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODc3NjgsImV4cCI6MjA2MzY2Mzc2OH0.0_qskeaC9axzevN44bhmFm6s6rTACqfND-PkIgzZ5eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);